### ISSUE TITLE
Add Route annotation → attribute for DeprecatedRoute

### ISSUE THREAD

**Issue by philiprabbett** [halloverden/symfony-route-deprecation-bundle#19]
See symfony/symfony#37474

**Comment by marco-giannetti** [comment]
Hello @philiprabbett, thanks for the issue, it sounds interesting. We'll come back to it as soon as we have time! If you want to give it a go, PRs are welcome!

**Comment by BafS** [comment]
This can be closed right?

**Comment by erichjsonfosse** [comment]
@BafS yes. Thanks for the heads up :+1:
