### ISSUE TITLE
Change to ISO 8601 date format

### ISSUE THREAD

**Issue by andreaslarssen** [halloverden/symfony-route-deprecation-bundle#9]
For version 2, consider changing to us date format (yyyy-mm-dd)

**Comment by marco-giannetti** [comment]
Isn't the US date format (mm-dd-yyyy)?
Anyway, I think both yyyy-mm-dd and dd-mm-yyyy formats are equally valid.
Is there any reason in particular why we might want to change?

**Comment by andreaslarssen** [comment]
No. https://www.wikiwand.com/en/Date_and_time_notation_in_the_United_States. 
But, it's really the ISO 8601 format: https://www.wikiwand.com/en/ISO_8601

**Comment by andreaslarssen** [comment]
The reason I want to change it, is because ISO 8601 is an international / de facto standard

**Comment by tomme87** [comment]
This is done
